apiVersion : apps/v1
kind: Deployment
metadata:
  name: "nick8s-9892"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "nick8s-9892"
  template:
    metadata:
      labels:
        app: "nick8s-9892"
    spec:
      containers:
        - name: "nick8s-9892"
          image: "nickk8sreg.azurecr.io/nick8s"
          ports:
          - containerPort: 8088