apiVersion: v1
kind: Service
metadata:
    name: "nick8s-9892"
    labels:
        app: "nick8s-9892"
spec:
    type: LoadBalancer
    ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: http
    selector:
        app: "nick8s-9892"